//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CityData.CityDataServiceReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CityDataServiceSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class CityDataService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAllCityDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataForCityOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCitiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddCityOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCityStatePairsOperationCompleted;
        
        private System.Threading.SendOrPostCallback Search_PopulationLessThanOperationCompleted;
        
        private System.Threading.SendOrPostCallback Search_PopulationEqualsOperationCompleted;
        
        private System.Threading.SendOrPostCallback Search_PopulationGreaterThanOperationCompleted;
        
        private System.Threading.SendOrPostCallback Search_MedianHouseholdIncomeLessThanOperationCompleted;
        
        private System.Threading.SendOrPostCallback Search_MedianHouseholdIncomeEqualsOperationCompleted;
        
        private System.Threading.SendOrPostCallback Search_MedianHouseholdIncomeGreaterThanOperationCompleted;
        
        private System.Threading.SendOrPostCallback Search_MedianHomeValueLessThanOperationCompleted;
        
        private System.Threading.SendOrPostCallback Search_MedianHomeValueEqualsOperationCompleted;
        
        private System.Threading.SendOrPostCallback Search_MedianHomeValueGreaterThanOperationCompleted;
        
        private System.Threading.SendOrPostCallback Search_MedianMaleAgeLessThanOperationCompleted;
        
        private System.Threading.SendOrPostCallback Search_MedianMaleAgeEqualsOperationCompleted;
        
        private System.Threading.SendOrPostCallback Search_MedianMaleAgeGreaterThanOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateCityOperationCompleted;
        
        private System.Threading.SendOrPostCallback PopulateCityTableOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CityDataService() {
            this.Url = global::CityData.Properties.Settings.Default.CityData_CityDataServiceReference_CityDataService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAllCityDataCompletedEventHandler GetAllCityDataCompleted;
        
        /// <remarks/>
        public event GetDataForCityCompletedEventHandler GetDataForCityCompleted;
        
        /// <remarks/>
        public event GetStatesCompletedEventHandler GetStatesCompleted;
        
        /// <remarks/>
        public event GetCitiesCompletedEventHandler GetCitiesCompleted;
        
        /// <remarks/>
        public event AddCityCompletedEventHandler AddCityCompleted;
        
        /// <remarks/>
        public event GetCityStatePairsCompletedEventHandler GetCityStatePairsCompleted;
        
        /// <remarks/>
        public event Search_PopulationLessThanCompletedEventHandler Search_PopulationLessThanCompleted;
        
        /// <remarks/>
        public event Search_PopulationEqualsCompletedEventHandler Search_PopulationEqualsCompleted;
        
        /// <remarks/>
        public event Search_PopulationGreaterThanCompletedEventHandler Search_PopulationGreaterThanCompleted;
        
        /// <remarks/>
        public event Search_MedianHouseholdIncomeLessThanCompletedEventHandler Search_MedianHouseholdIncomeLessThanCompleted;
        
        /// <remarks/>
        public event Search_MedianHouseholdIncomeEqualsCompletedEventHandler Search_MedianHouseholdIncomeEqualsCompleted;
        
        /// <remarks/>
        public event Search_MedianHouseholdIncomeGreaterThanCompletedEventHandler Search_MedianHouseholdIncomeGreaterThanCompleted;
        
        /// <remarks/>
        public event Search_MedianHomeValueLessThanCompletedEventHandler Search_MedianHomeValueLessThanCompleted;
        
        /// <remarks/>
        public event Search_MedianHomeValueEqualsCompletedEventHandler Search_MedianHomeValueEqualsCompleted;
        
        /// <remarks/>
        public event Search_MedianHomeValueGreaterThanCompletedEventHandler Search_MedianHomeValueGreaterThanCompleted;
        
        /// <remarks/>
        public event Search_MedianMaleAgeLessThanCompletedEventHandler Search_MedianMaleAgeLessThanCompleted;
        
        /// <remarks/>
        public event Search_MedianMaleAgeEqualsCompletedEventHandler Search_MedianMaleAgeEqualsCompleted;
        
        /// <remarks/>
        public event Search_MedianMaleAgeGreaterThanCompletedEventHandler Search_MedianMaleAgeGreaterThanCompleted;
        
        /// <remarks/>
        public event UpdateCityCompletedEventHandler UpdateCityCompleted;
        
        /// <remarks/>
        public event PopulateCityTableCompletedEventHandler PopulateCityTableCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllCityData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] GetAllCityData() {
            object[] results = this.Invoke("GetAllCityData", new object[0]);
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllCityDataAsync() {
            this.GetAllCityDataAsync(null);
        }
        
        /// <remarks/>
        public void GetAllCityDataAsync(object userState) {
            if ((this.GetAllCityDataOperationCompleted == null)) {
                this.GetAllCityDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllCityDataOperationCompleted);
            }
            this.InvokeAsync("GetAllCityData", new object[0], this.GetAllCityDataOperationCompleted, userState);
        }
        
        private void OnGetAllCityDataOperationCompleted(object arg) {
            if ((this.GetAllCityDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllCityDataCompleted(this, new GetAllCityDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDataForCity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public City GetDataForCity(string city, string state) {
            object[] results = this.Invoke("GetDataForCity", new object[] {
                        city,
                        state});
            return ((City)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataForCityAsync(string city, string state) {
            this.GetDataForCityAsync(city, state, null);
        }
        
        /// <remarks/>
        public void GetDataForCityAsync(string city, string state, object userState) {
            if ((this.GetDataForCityOperationCompleted == null)) {
                this.GetDataForCityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataForCityOperationCompleted);
            }
            this.InvokeAsync("GetDataForCity", new object[] {
                        city,
                        state}, this.GetDataForCityOperationCompleted, userState);
        }
        
        private void OnGetDataForCityOperationCompleted(object arg) {
            if ((this.GetDataForCityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataForCityCompleted(this, new GetDataForCityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStates", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetStates() {
            object[] results = this.Invoke("GetStates", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetStatesAsync() {
            this.GetStatesAsync(null);
        }
        
        /// <remarks/>
        public void GetStatesAsync(object userState) {
            if ((this.GetStatesOperationCompleted == null)) {
                this.GetStatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStatesOperationCompleted);
            }
            this.InvokeAsync("GetStates", new object[0], this.GetStatesOperationCompleted, userState);
        }
        
        private void OnGetStatesOperationCompleted(object arg) {
            if ((this.GetStatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStatesCompleted(this, new GetStatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCities", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetCities(string state) {
            object[] results = this.Invoke("GetCities", new object[] {
                        state});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetCitiesAsync(string state) {
            this.GetCitiesAsync(state, null);
        }
        
        /// <remarks/>
        public void GetCitiesAsync(string state, object userState) {
            if ((this.GetCitiesOperationCompleted == null)) {
                this.GetCitiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCitiesOperationCompleted);
            }
            this.InvokeAsync("GetCities", new object[] {
                        state}, this.GetCitiesOperationCompleted, userState);
        }
        
        private void OnGetCitiesOperationCompleted(object arg) {
            if ((this.GetCitiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCitiesCompleted(this, new GetCitiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddCity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddCity(City city) {
            object[] results = this.Invoke("AddCity", new object[] {
                        city});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddCityAsync(City city) {
            this.AddCityAsync(city, null);
        }
        
        /// <remarks/>
        public void AddCityAsync(City city, object userState) {
            if ((this.AddCityOperationCompleted == null)) {
                this.AddCityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddCityOperationCompleted);
            }
            this.InvokeAsync("AddCity", new object[] {
                        city}, this.AddCityOperationCompleted, userState);
        }
        
        private void OnAddCityOperationCompleted(object arg) {
            if ((this.AddCityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddCityCompleted(this, new AddCityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCityStatePairs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetCityStatePairs() {
            object[] results = this.Invoke("GetCityStatePairs", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetCityStatePairsAsync() {
            this.GetCityStatePairsAsync(null);
        }
        
        /// <remarks/>
        public void GetCityStatePairsAsync(object userState) {
            if ((this.GetCityStatePairsOperationCompleted == null)) {
                this.GetCityStatePairsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCityStatePairsOperationCompleted);
            }
            this.InvokeAsync("GetCityStatePairs", new object[0], this.GetCityStatePairsOperationCompleted, userState);
        }
        
        private void OnGetCityStatePairsOperationCompleted(object arg) {
            if ((this.GetCityStatePairsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCityStatePairsCompleted(this, new GetCityStatePairsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Search_PopulationLessThan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] Search_PopulationLessThan(int value) {
            object[] results = this.Invoke("Search_PopulationLessThan", new object[] {
                        value});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void Search_PopulationLessThanAsync(int value) {
            this.Search_PopulationLessThanAsync(value, null);
        }
        
        /// <remarks/>
        public void Search_PopulationLessThanAsync(int value, object userState) {
            if ((this.Search_PopulationLessThanOperationCompleted == null)) {
                this.Search_PopulationLessThanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearch_PopulationLessThanOperationCompleted);
            }
            this.InvokeAsync("Search_PopulationLessThan", new object[] {
                        value}, this.Search_PopulationLessThanOperationCompleted, userState);
        }
        
        private void OnSearch_PopulationLessThanOperationCompleted(object arg) {
            if ((this.Search_PopulationLessThanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Search_PopulationLessThanCompleted(this, new Search_PopulationLessThanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Search_PopulationEquals", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] Search_PopulationEquals(int value) {
            object[] results = this.Invoke("Search_PopulationEquals", new object[] {
                        value});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void Search_PopulationEqualsAsync(int value) {
            this.Search_PopulationEqualsAsync(value, null);
        }
        
        /// <remarks/>
        public void Search_PopulationEqualsAsync(int value, object userState) {
            if ((this.Search_PopulationEqualsOperationCompleted == null)) {
                this.Search_PopulationEqualsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearch_PopulationEqualsOperationCompleted);
            }
            this.InvokeAsync("Search_PopulationEquals", new object[] {
                        value}, this.Search_PopulationEqualsOperationCompleted, userState);
        }
        
        private void OnSearch_PopulationEqualsOperationCompleted(object arg) {
            if ((this.Search_PopulationEqualsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Search_PopulationEqualsCompleted(this, new Search_PopulationEqualsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Search_PopulationGreaterThan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] Search_PopulationGreaterThan(int value) {
            object[] results = this.Invoke("Search_PopulationGreaterThan", new object[] {
                        value});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void Search_PopulationGreaterThanAsync(int value) {
            this.Search_PopulationGreaterThanAsync(value, null);
        }
        
        /// <remarks/>
        public void Search_PopulationGreaterThanAsync(int value, object userState) {
            if ((this.Search_PopulationGreaterThanOperationCompleted == null)) {
                this.Search_PopulationGreaterThanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearch_PopulationGreaterThanOperationCompleted);
            }
            this.InvokeAsync("Search_PopulationGreaterThan", new object[] {
                        value}, this.Search_PopulationGreaterThanOperationCompleted, userState);
        }
        
        private void OnSearch_PopulationGreaterThanOperationCompleted(object arg) {
            if ((this.Search_PopulationGreaterThanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Search_PopulationGreaterThanCompleted(this, new Search_PopulationGreaterThanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Search_MedianHouseholdIncomeLessThan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] Search_MedianHouseholdIncomeLessThan(int value) {
            object[] results = this.Invoke("Search_MedianHouseholdIncomeLessThan", new object[] {
                        value});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void Search_MedianHouseholdIncomeLessThanAsync(int value) {
            this.Search_MedianHouseholdIncomeLessThanAsync(value, null);
        }
        
        /// <remarks/>
        public void Search_MedianHouseholdIncomeLessThanAsync(int value, object userState) {
            if ((this.Search_MedianHouseholdIncomeLessThanOperationCompleted == null)) {
                this.Search_MedianHouseholdIncomeLessThanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearch_MedianHouseholdIncomeLessThanOperationCompleted);
            }
            this.InvokeAsync("Search_MedianHouseholdIncomeLessThan", new object[] {
                        value}, this.Search_MedianHouseholdIncomeLessThanOperationCompleted, userState);
        }
        
        private void OnSearch_MedianHouseholdIncomeLessThanOperationCompleted(object arg) {
            if ((this.Search_MedianHouseholdIncomeLessThanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Search_MedianHouseholdIncomeLessThanCompleted(this, new Search_MedianHouseholdIncomeLessThanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Search_MedianHouseholdIncomeEquals", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] Search_MedianHouseholdIncomeEquals(int value) {
            object[] results = this.Invoke("Search_MedianHouseholdIncomeEquals", new object[] {
                        value});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void Search_MedianHouseholdIncomeEqualsAsync(int value) {
            this.Search_MedianHouseholdIncomeEqualsAsync(value, null);
        }
        
        /// <remarks/>
        public void Search_MedianHouseholdIncomeEqualsAsync(int value, object userState) {
            if ((this.Search_MedianHouseholdIncomeEqualsOperationCompleted == null)) {
                this.Search_MedianHouseholdIncomeEqualsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearch_MedianHouseholdIncomeEqualsOperationCompleted);
            }
            this.InvokeAsync("Search_MedianHouseholdIncomeEquals", new object[] {
                        value}, this.Search_MedianHouseholdIncomeEqualsOperationCompleted, userState);
        }
        
        private void OnSearch_MedianHouseholdIncomeEqualsOperationCompleted(object arg) {
            if ((this.Search_MedianHouseholdIncomeEqualsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Search_MedianHouseholdIncomeEqualsCompleted(this, new Search_MedianHouseholdIncomeEqualsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Search_MedianHouseholdIncomeGreaterThan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] Search_MedianHouseholdIncomeGreaterThan(int value) {
            object[] results = this.Invoke("Search_MedianHouseholdIncomeGreaterThan", new object[] {
                        value});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void Search_MedianHouseholdIncomeGreaterThanAsync(int value) {
            this.Search_MedianHouseholdIncomeGreaterThanAsync(value, null);
        }
        
        /// <remarks/>
        public void Search_MedianHouseholdIncomeGreaterThanAsync(int value, object userState) {
            if ((this.Search_MedianHouseholdIncomeGreaterThanOperationCompleted == null)) {
                this.Search_MedianHouseholdIncomeGreaterThanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearch_MedianHouseholdIncomeGreaterThanOperationCompleted);
            }
            this.InvokeAsync("Search_MedianHouseholdIncomeGreaterThan", new object[] {
                        value}, this.Search_MedianHouseholdIncomeGreaterThanOperationCompleted, userState);
        }
        
        private void OnSearch_MedianHouseholdIncomeGreaterThanOperationCompleted(object arg) {
            if ((this.Search_MedianHouseholdIncomeGreaterThanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Search_MedianHouseholdIncomeGreaterThanCompleted(this, new Search_MedianHouseholdIncomeGreaterThanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Search_MedianHomeValueLessThan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] Search_MedianHomeValueLessThan(int value) {
            object[] results = this.Invoke("Search_MedianHomeValueLessThan", new object[] {
                        value});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void Search_MedianHomeValueLessThanAsync(int value) {
            this.Search_MedianHomeValueLessThanAsync(value, null);
        }
        
        /// <remarks/>
        public void Search_MedianHomeValueLessThanAsync(int value, object userState) {
            if ((this.Search_MedianHomeValueLessThanOperationCompleted == null)) {
                this.Search_MedianHomeValueLessThanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearch_MedianHomeValueLessThanOperationCompleted);
            }
            this.InvokeAsync("Search_MedianHomeValueLessThan", new object[] {
                        value}, this.Search_MedianHomeValueLessThanOperationCompleted, userState);
        }
        
        private void OnSearch_MedianHomeValueLessThanOperationCompleted(object arg) {
            if ((this.Search_MedianHomeValueLessThanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Search_MedianHomeValueLessThanCompleted(this, new Search_MedianHomeValueLessThanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Search_MedianHomeValueEquals", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] Search_MedianHomeValueEquals(int value) {
            object[] results = this.Invoke("Search_MedianHomeValueEquals", new object[] {
                        value});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void Search_MedianHomeValueEqualsAsync(int value) {
            this.Search_MedianHomeValueEqualsAsync(value, null);
        }
        
        /// <remarks/>
        public void Search_MedianHomeValueEqualsAsync(int value, object userState) {
            if ((this.Search_MedianHomeValueEqualsOperationCompleted == null)) {
                this.Search_MedianHomeValueEqualsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearch_MedianHomeValueEqualsOperationCompleted);
            }
            this.InvokeAsync("Search_MedianHomeValueEquals", new object[] {
                        value}, this.Search_MedianHomeValueEqualsOperationCompleted, userState);
        }
        
        private void OnSearch_MedianHomeValueEqualsOperationCompleted(object arg) {
            if ((this.Search_MedianHomeValueEqualsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Search_MedianHomeValueEqualsCompleted(this, new Search_MedianHomeValueEqualsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Search_MedianHomeValueGreaterThan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] Search_MedianHomeValueGreaterThan(int value) {
            object[] results = this.Invoke("Search_MedianHomeValueGreaterThan", new object[] {
                        value});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void Search_MedianHomeValueGreaterThanAsync(int value) {
            this.Search_MedianHomeValueGreaterThanAsync(value, null);
        }
        
        /// <remarks/>
        public void Search_MedianHomeValueGreaterThanAsync(int value, object userState) {
            if ((this.Search_MedianHomeValueGreaterThanOperationCompleted == null)) {
                this.Search_MedianHomeValueGreaterThanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearch_MedianHomeValueGreaterThanOperationCompleted);
            }
            this.InvokeAsync("Search_MedianHomeValueGreaterThan", new object[] {
                        value}, this.Search_MedianHomeValueGreaterThanOperationCompleted, userState);
        }
        
        private void OnSearch_MedianHomeValueGreaterThanOperationCompleted(object arg) {
            if ((this.Search_MedianHomeValueGreaterThanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Search_MedianHomeValueGreaterThanCompleted(this, new Search_MedianHomeValueGreaterThanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Search_MedianMaleAgeLessThan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] Search_MedianMaleAgeLessThan(int value) {
            object[] results = this.Invoke("Search_MedianMaleAgeLessThan", new object[] {
                        value});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void Search_MedianMaleAgeLessThanAsync(int value) {
            this.Search_MedianMaleAgeLessThanAsync(value, null);
        }
        
        /// <remarks/>
        public void Search_MedianMaleAgeLessThanAsync(int value, object userState) {
            if ((this.Search_MedianMaleAgeLessThanOperationCompleted == null)) {
                this.Search_MedianMaleAgeLessThanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearch_MedianMaleAgeLessThanOperationCompleted);
            }
            this.InvokeAsync("Search_MedianMaleAgeLessThan", new object[] {
                        value}, this.Search_MedianMaleAgeLessThanOperationCompleted, userState);
        }
        
        private void OnSearch_MedianMaleAgeLessThanOperationCompleted(object arg) {
            if ((this.Search_MedianMaleAgeLessThanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Search_MedianMaleAgeLessThanCompleted(this, new Search_MedianMaleAgeLessThanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Search_MedianMaleAgeEquals", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] Search_MedianMaleAgeEquals(int value) {
            object[] results = this.Invoke("Search_MedianMaleAgeEquals", new object[] {
                        value});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void Search_MedianMaleAgeEqualsAsync(int value) {
            this.Search_MedianMaleAgeEqualsAsync(value, null);
        }
        
        /// <remarks/>
        public void Search_MedianMaleAgeEqualsAsync(int value, object userState) {
            if ((this.Search_MedianMaleAgeEqualsOperationCompleted == null)) {
                this.Search_MedianMaleAgeEqualsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearch_MedianMaleAgeEqualsOperationCompleted);
            }
            this.InvokeAsync("Search_MedianMaleAgeEquals", new object[] {
                        value}, this.Search_MedianMaleAgeEqualsOperationCompleted, userState);
        }
        
        private void OnSearch_MedianMaleAgeEqualsOperationCompleted(object arg) {
            if ((this.Search_MedianMaleAgeEqualsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Search_MedianMaleAgeEqualsCompleted(this, new Search_MedianMaleAgeEqualsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Search_MedianMaleAgeGreaterThan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] Search_MedianMaleAgeGreaterThan(int value) {
            object[] results = this.Invoke("Search_MedianMaleAgeGreaterThan", new object[] {
                        value});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void Search_MedianMaleAgeGreaterThanAsync(int value) {
            this.Search_MedianMaleAgeGreaterThanAsync(value, null);
        }
        
        /// <remarks/>
        public void Search_MedianMaleAgeGreaterThanAsync(int value, object userState) {
            if ((this.Search_MedianMaleAgeGreaterThanOperationCompleted == null)) {
                this.Search_MedianMaleAgeGreaterThanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearch_MedianMaleAgeGreaterThanOperationCompleted);
            }
            this.InvokeAsync("Search_MedianMaleAgeGreaterThan", new object[] {
                        value}, this.Search_MedianMaleAgeGreaterThanOperationCompleted, userState);
        }
        
        private void OnSearch_MedianMaleAgeGreaterThanOperationCompleted(object arg) {
            if ((this.Search_MedianMaleAgeGreaterThanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Search_MedianMaleAgeGreaterThanCompleted(this, new Search_MedianMaleAgeGreaterThanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateCity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateCity(City city) {
            object[] results = this.Invoke("UpdateCity", new object[] {
                        city});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateCityAsync(City city) {
            this.UpdateCityAsync(city, null);
        }
        
        /// <remarks/>
        public void UpdateCityAsync(City city, object userState) {
            if ((this.UpdateCityOperationCompleted == null)) {
                this.UpdateCityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateCityOperationCompleted);
            }
            this.InvokeAsync("UpdateCity", new object[] {
                        city}, this.UpdateCityOperationCompleted, userState);
        }
        
        private void OnUpdateCityOperationCompleted(object arg) {
            if ((this.UpdateCityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCityCompleted(this, new UpdateCityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PopulateCityTable", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void PopulateCityTable() {
            this.Invoke("PopulateCityTable", new object[0]);
        }
        
        /// <remarks/>
        public void PopulateCityTableAsync() {
            this.PopulateCityTableAsync(null);
        }
        
        /// <remarks/>
        public void PopulateCityTableAsync(object userState) {
            if ((this.PopulateCityTableOperationCompleted == null)) {
                this.PopulateCityTableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPopulateCityTableOperationCompleted);
            }
            this.InvokeAsync("PopulateCityTable", new object[0], this.PopulateCityTableOperationCompleted, userState);
        }
        
        private void OnPopulateCityTableOperationCompleted(object arg) {
            if ((this.PopulateCityTableCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PopulateCityTableCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class City {
        
        private string cityNameField;
        
        private string stateField;
        
        private int populationField;
        
        private int medianHouseholdIncomeField;
        
        private decimal percentOwnersField;
        
        private decimal percentRentersField;
        
        private int medianHomeValueField;
        
        private int medianMaleAgeField;
        
        private int medianFemaleAgeField;
        
        private decimal unemploymentRateField;
        
        private decimal crimeIndexField;
        
        /// <remarks/>
        public string CityName {
            get {
                return this.cityNameField;
            }
            set {
                this.cityNameField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public int Population {
            get {
                return this.populationField;
            }
            set {
                this.populationField = value;
            }
        }
        
        /// <remarks/>
        public int MedianHouseholdIncome {
            get {
                return this.medianHouseholdIncomeField;
            }
            set {
                this.medianHouseholdIncomeField = value;
            }
        }
        
        /// <remarks/>
        public decimal PercentOwners {
            get {
                return this.percentOwnersField;
            }
            set {
                this.percentOwnersField = value;
            }
        }
        
        /// <remarks/>
        public decimal PercentRenters {
            get {
                return this.percentRentersField;
            }
            set {
                this.percentRentersField = value;
            }
        }
        
        /// <remarks/>
        public int MedianHomeValue {
            get {
                return this.medianHomeValueField;
            }
            set {
                this.medianHomeValueField = value;
            }
        }
        
        /// <remarks/>
        public int MedianMaleAge {
            get {
                return this.medianMaleAgeField;
            }
            set {
                this.medianMaleAgeField = value;
            }
        }
        
        /// <remarks/>
        public int MedianFemaleAge {
            get {
                return this.medianFemaleAgeField;
            }
            set {
                this.medianFemaleAgeField = value;
            }
        }
        
        /// <remarks/>
        public decimal UnemploymentRate {
            get {
                return this.unemploymentRateField;
            }
            set {
                this.unemploymentRateField = value;
            }
        }
        
        /// <remarks/>
        public decimal CrimeIndex {
            get {
                return this.crimeIndexField;
            }
            set {
                this.crimeIndexField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetAllCityDataCompletedEventHandler(object sender, GetAllCityDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllCityDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllCityDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetDataForCityCompletedEventHandler(object sender, GetDataForCityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataForCityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataForCityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public City Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((City)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetStatesCompletedEventHandler(object sender, GetStatesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetCitiesCompletedEventHandler(object sender, GetCitiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCitiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCitiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void AddCityCompletedEventHandler(object sender, AddCityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddCityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddCityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetCityStatePairsCompletedEventHandler(object sender, GetCityStatePairsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCityStatePairsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCityStatePairsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void Search_PopulationLessThanCompletedEventHandler(object sender, Search_PopulationLessThanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Search_PopulationLessThanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Search_PopulationLessThanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void Search_PopulationEqualsCompletedEventHandler(object sender, Search_PopulationEqualsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Search_PopulationEqualsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Search_PopulationEqualsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void Search_PopulationGreaterThanCompletedEventHandler(object sender, Search_PopulationGreaterThanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Search_PopulationGreaterThanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Search_PopulationGreaterThanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void Search_MedianHouseholdIncomeLessThanCompletedEventHandler(object sender, Search_MedianHouseholdIncomeLessThanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Search_MedianHouseholdIncomeLessThanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Search_MedianHouseholdIncomeLessThanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void Search_MedianHouseholdIncomeEqualsCompletedEventHandler(object sender, Search_MedianHouseholdIncomeEqualsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Search_MedianHouseholdIncomeEqualsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Search_MedianHouseholdIncomeEqualsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void Search_MedianHouseholdIncomeGreaterThanCompletedEventHandler(object sender, Search_MedianHouseholdIncomeGreaterThanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Search_MedianHouseholdIncomeGreaterThanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Search_MedianHouseholdIncomeGreaterThanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void Search_MedianHomeValueLessThanCompletedEventHandler(object sender, Search_MedianHomeValueLessThanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Search_MedianHomeValueLessThanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Search_MedianHomeValueLessThanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void Search_MedianHomeValueEqualsCompletedEventHandler(object sender, Search_MedianHomeValueEqualsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Search_MedianHomeValueEqualsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Search_MedianHomeValueEqualsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void Search_MedianHomeValueGreaterThanCompletedEventHandler(object sender, Search_MedianHomeValueGreaterThanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Search_MedianHomeValueGreaterThanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Search_MedianHomeValueGreaterThanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void Search_MedianMaleAgeLessThanCompletedEventHandler(object sender, Search_MedianMaleAgeLessThanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Search_MedianMaleAgeLessThanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Search_MedianMaleAgeLessThanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void Search_MedianMaleAgeEqualsCompletedEventHandler(object sender, Search_MedianMaleAgeEqualsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Search_MedianMaleAgeEqualsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Search_MedianMaleAgeEqualsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void Search_MedianMaleAgeGreaterThanCompletedEventHandler(object sender, Search_MedianMaleAgeGreaterThanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Search_MedianMaleAgeGreaterThanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Search_MedianMaleAgeGreaterThanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void UpdateCityCompletedEventHandler(object sender, UpdateCityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void PopulateCityTableCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591